### ISSUE TITLE
Publishing under UU through github desktop is not straightforward

### ISSUE THREAD

**Issue by fliepeltje** [UtrechtUniversity/getting-started#12]
When using Github Desktop to publish a repository to the Utrecht University organization, you get an error with the origin. This presumably has to do with the SSO setting; how necessary is the SSO? What benefits does it provide? Because the barrier of entry is considerably increased because of it.

**Comment by jelletreep** [comment]
I think SSO should not be the issue here, but it is not straightforward and I am not sure where things go wrong. I'll try to help people out and get a better view on where things are going wrong so we can add good instructions to the documentation

**Comment by J535D165** [comment]
Can you share the error message?

**Comment by fliepeltje** [comment]
> Can you share the error message?

This is related to #15 - that's the error that came up. I tried to use gh desktop from a fresh install and zero configuration and it seemed to work (though from a linux machine), so it might be a one-off problem here. I'll close this a s a duplicate
