### ISSUE TITLE
Permission issue with publishing to UtrechtUniversity organisation

### ISSUE THREAD

**Issue by TomSchermer** [UtrechtUniversity/getting-started#15]
![Permission_error_while_publishing_repository_UU](https://user-images.githubusercontent.com/132554795/236174955-f09af25c-fff2-4062-b031-26b7a3216593.jpg)

I tried to recreate an earlier publishing error "fatal error in commit_refs", but whilst setting up for that ran into this one.

**Comment by jelletreep** [comment]
Hi Tom,
I cannot reproduce the issue, so it hard to troubleshoot. Can we have a quick teams call to see what is wrong?
I'll send you a message

**Comment by jelletreep** [comment]
Solved for now. We couldn't reproduce so the source of the error is unknown
