### ISSUE TITLE
UMC vs UU

### ISSUE THREAD

**Issue by swvanderlaan** [UtrechtUniversity/getting-started#3]
First of all: wow, what a great Team page for the UU did you make. 

Second: I'd love to become a member, but the 4th step in your `readme` doesn't work for me. I am an UMC employee and therefore my SolisID is limited and the authentication fails (likely because of this limitation). Any other way to become a member? 

Best,

Sander

**Comment by J535D165** [comment]
@swvanderlaan Thanks. UMC employees with SolisID should have access to the GitHub service (as far as I know). Apparently, this is not the case. I will ask the GitHub UU administrator to respond to this issue.

**Comment by Sabaj101** [comment]
@swvanderlaan 
It might be that you have a guest SolisID. The solution will be to apply for a staff SolisID. As far as I know every UMCU employee can apply for one. Please ask your ICT department for procedure. 

Mind you that as of the 8th of November 2-factor authentication (2-FA) is required to log into UtrechtUniversity organization. To set up 2-FA, see https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication.

**Comment by jelletreep** [comment]
@swvanderlaan 
We investigated this a bit further and apparently there needs to be a change in the configuration to give access to UMCU employees. We are working on it, but it may take a few days. We will keep you up to date.

**Comment by jelletreep** [comment]
@swvanderlaan 
It should be possible now for UMCU staff to get access to the organization, could you check and report back to us?

**Comment by J535D165** [comment]
I'm closing this issue, feel free to reopen it if the access issue is still there.
