### ISSUE TITLE
Work responsibly

### ISSUE THREAD

**Issue by hugoquene** [UtrechtUniversity/getting-started#5]
In the Readme.md file, the section heading "Work responsible" should probably be "Work responsibly". 
Background: "responsible" is an adjective modifying a noun (analogous to "happy", but then it should precede and not follow the noun), "responsibly" is an adverb modifying a verb (analogous to "happily"), which seems to be intended here.

**Comment by jelletreep** [comment]
Thank you for the feedback, i will change it!
