### ISSUE TITLE
Request to add Microsoft Azure Data Factory application

### ISSUE THREAD

**Issue by uaksu** [UtrechtUniversity/getting-started#8]
Dear Organizational Repository Admins,

For our [Learning Analytics](https://www.uu.nl/en/education/learning-analytics) projects, we use Microsoft Azure services. To store the project code in our Azure Data Factory implementations, we need application access. Can you please add the required permission for the application ( https://github.com/AzureDataFactory ).

Regards,
[Team LA UU](https://www.uu.nl/en/education/learning-analytics/la-in-education)

**Comment by J535D165** [comment]
Hi @uaksu 

Please reach out to Jelle Treep or Lloyd Sabajo by email. They are the admins.

Best Jonathan

**Comment by jelletreep** [comment]
solved
